name: Save Quiz Results

on:
  workflow_dispatch:
    inputs:
      player_name:
        description: 'Player Name'
        required: true
      score:
        description: 'Quiz Score'
        required: true
      total_questions:
        description: 'Total Questions'
        required: true
      result_text:
        description: 'Quiz Result Text'
        required: true

jobs:
  save_results:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read current results from results.json
        id: read_results
        run: |
          if [[ -f results.json ]]; then
            results=$(cat results.json)
          else
            results="[]"
          fi
          echo "results=$results" >> $GITHUB_ENV

      - name: Add result to results.json
        run: |
          new_result="{\"player_name\": \"${{ github.event.inputs.player_name }}\", \"score\": \"${{ github.event.inputs.score }}\", \"total_questions\": \"${{ github.event.inputs.total_questions }}\", \"result_text\": \"${{ github.event.inputs.result_text }}\"}"
          updated_results="${{ env.results }}"
          updated_results=$(echo $updated_results | jq ". + [$new_result]")
          echo $updated_results > results.json

      - name: Commit and push results
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add results.json
          git diff --quiet --exit-code || (git commit -m "Add quiz result for ${{ github.event.inputs.player_name }}" && git push)
